project:
  type: website
  output-dir: docs

website:
  title: "lindsayevanslee.com"
  description: "Lindsay Lee's website"
  favicon: "images/favicon.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cv.qmd
      - research.qmd
      - writing.qmd
      - news.qmd
      - blog.qmd
      - lindsaycodes.qmd

format:
  html:
    theme: simplex
    css: styles.css
    #theme: simplex_custom.scss
    toc: true
    header-includes: <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito&display=swap">
    mainfont: Nunito
    #header-includes: <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap">
    #mainfont: Roboto

resources:
  - CNAME

editor: visual

