project:
  type: website
  output-dir: docs

website:
  title: "lindsayevanslee.com"
  description: "Lindsay Lee's website"
  favicon: "images/favicon.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cv.qmd
      - research.qmd
      - writing.qmd
      - news.qmd
      - blog.qmd
      - lindsaycodes.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    header-includes: <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito&display=swap">
    mainfont: Nunito

resources:
  - CNAME

editor: visual

