---
title: "In the News"
---

## At WHO

[NIH Office of Disease Prevention webinar](https://prevention.nih.gov/education-training/prevention-focus-webinars/world-health-organization-who-guidelines-physical-activity-and-sedentary-behavior-persons) on WHO Guidelines on Physical Activity and Sedentary Behavior for Persons with Disabilities (October 18, 2022)

[Twitter live stream](https://twitter.com/WHO/status/1240614100473790474?s=20) Q&A on disability and COVID-19 (also on [Facebook](https://www.facebook.com/WHO/videos/227432915115053/) and [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:6646379836346515457)) (March 19, 2020)

[United Nations News](https://news.un.org/en/story/2020/03/1059762) piece on preventing discrimination against people with disabilities in the COVID-19 response (March 19, 2020)

[TV3 Ghana news story](https://www.youtube.com/watch?feature=youtu.be&v=Usteqduaas0) about coronavirus and disability

[Yahoo Lifestyle](https://www.yahoo.com/lifestyle/the-coronavirus-and-people-with-disabilities-214936915.html) piece on WHO highlighting COVID-19 and people with disabilities (March 20, 2020)

## At Oxford

[Press release](https://www.wadham.ox.ac.uk/news/2015/november/disability-advocacy-and-the-law) after second annual Herbert Smith Freehills Disability Mooting Championship and Conversazione (November 11, 2015)

[*Women at Wadham College: Past, Present and Future*](https://www.wadham.ox.ac.uk/news/2015/june/film-women-at-wadham--past-present-and-future) documentary about the evolving female experience at Wadham (June 22, 2015)

*Cherwell* stories on motions I seconded in OUSU Council (Oxford's student union) about referenda on [sub fusc](http://www.cherwell.org/news/topstories/2015/03/06/ousu-to-hold-universitywide-referendum-on-subfusc) and [reading weeks](http://www.cherwell.org/news/topstories/2015/03/06/motion-to-open-up-discussion-of-reading-weeks-passes) (March 6, 2015)

[Press release](https://www.law.ox.ac.uk/news/2014-11-26-inaugural-herbert-smith-freehills-oxford-disability-mooting-championship-%C2%91real) after inaugural Herbert Smith Freehills Disability Mooting Championship and Conversazione (November 26, 2014)

[*Cherwell*](http://www.cherwell.org/news/town/2014/11/15/ousu-hustings-move-to-accessible-venues) story on my OUSU team's boycotting of inaccessible husting venues during the campaign (November 15, 2014)

## Winning the Rhodes Scholarship

[WBIR](http://downtown.wbir.com/news/news/630012-ut-senior-one-32-students-named-rhodes-scholar) story (November 25, 2013)

[*Tennessee Today*](http://tntoday.utk.edu/2013/11/25/lindsay-lee-named-rhodes-scholar/) from the University of Tennessee (November 25, 2013)

A [column](http://www.utdailybeacon.com/opinion/lindsay-lee-rhodes-scholar/article_eabd69f2-0a1e-5ff7-81e7-70a2b8c4cb6c.html) and [letter to the editor](http://www.utdailybeacon.com/opinion/an-ode-to-rhodes-scholar-lindsay-lee/article_8fa2cb41-8a04-5b56-84bd-24b43d7b5c02.html) in *The Daily Beacon* by my dear friends (November 25-26, 2013)

[*Oak Ridger*](http://www.oakridger.com/article/20131217/NEWS/131219923) story about proclamation from my hometown (December 17, 2013)

University of Tennessee video (below) (November 26, 2013):

<iframe width="560" height="315" src="https://www.youtube.com/embed/bDKEKX1GGs8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

## In Tennessee

Oak Ridge profile ([Part 1](https://www.oakridger.com/news/20200124/remarkable-life-of-orhs-grad-lindsay-lee) and [Part 2](https://www.oakridger.com/news/20200211/historically-speaking-extraordinary-adult-life-of-lindsay-lee)) about me by my high school math teacher (January 24 and February 11, 2020)

My [op-ed](http://www.tennessean.com/story/opinion/contributors/2016/04/18/university-tennessee-rhodes-scholars-back-diversity/83216744/) in the *Tennesseean*, co-written with fellow UT Rhodes Scholar [Robert Fisher](https://twitter.com/robert_fisher1), opposing the proposed cuts to the Office of Diversity and Inclusion at the University of Tennessee (April 18, 2016)

[*Quest Magazine*](http://quest.utk.edu/2014/doing-the-math/) on feral cats project (May 29, 2014)

[*Tennessee Today*](http://tntoday.utk.edu/2013/02/27/students-finalists-truman-scholarships/) about Truman Scholarship Finalist (February 27, 2013)

[*Tennessee Journalist*](http://tnjn.org/2013/mar/19/video-amplify-ut-pushes-indivi/) about Amplify UT student government campaign (March 19, 2013)

[*Oak Ridger*](http://www.oakridger.com/article/20090827/NEWS/308279977) story about removing barriers with my high school history teacher at the Gettysburg National Military Park (August 27, 2009)

## Other stories

[Q&A](http://www.ifes.org/news/ifes-qa-former-inclusion-intern-program-development-innovation-lindsay-lee) with International Foundation for Electoral Issues (September 14, 2014)

[Muscular Dystrophy Association](http://quest.mda.org/news/math-and-md) high school profile (December 3, 2009)
