---
title: "Writing"
---

Here are some pieces that I've published.

* * * * *

[Section](https://www.law.ox.ac.uk/sites/files/oxlaw/lindsay_lee.pdf) on "Disabled People's Access to Healthcare Services" in the [report](https://www.law.ox.ac.uk/news/2020-07-02-affront-dignity-inclusion-and-equality-coronavirus-and-impact-law-policy-practice) *An Affront to Dignity, Inclusion and Equality: Coronavirus and the Impact of Law, Policy, Practice and Access to Services on People with Disabilities in the United Kingdom* From the Oxford University Disability Law & Policy Project (July 2, 2020)

[Article](http://www.wadham.ox.ac.uk/docs/201609WadhamJournal_1473932478.pdf) in the *Wadham Journal: The Disability Issue* critiquing the use of disability-adjusted life years (DALYs) as the measurement tool for disease burden in public health policy (September 21, 2016)

[Blog post](http://blogs.bsg.ox.ac.uk/2016/07/19/inclusivity-through-accessiblility-at-the-blavatnik-school-of-government/) for the Blavatnik School of Government about the new building, accessibility, and the importance of inclusive communities (July 19, 2016)

[Op-ed](http://www.tennessean.com/story/opinion/contributors/2016/04/18/university-tennessee-rhodes-scholars-back-diversity/83216744/) in the *Tennesseean*, co-written with fellow UT Rhodes Scholar [Robert Fisher](https://twitter.com/robert_fisher1), opposing the proposed cuts to the Office of Diversity and Inclusion at the University of Tennessee (April 18, 2016)
